// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mombasa.proto
#ifndef GRPC_mombasa_2eproto__INCLUDED
#define GRPC_mombasa_2eproto__INCLUDED

#include "mombasa.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace mombasa {

class MombasaBridge final {
 public:
  static constexpr char const* service_full_name() {
    return "mombasa.MombasaBridge";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CallFunction(::grpc::ClientContext* context, const ::mombasa::CallRequest& request, ::mombasa::CallResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::CallResponse>> AsyncCallFunction(::grpc::ClientContext* context, const ::mombasa::CallRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::CallResponse>>(AsyncCallFunctionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::CallResponse>> PrepareAsyncCallFunction(::grpc::ClientContext* context, const ::mombasa::CallRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::CallResponse>>(PrepareAsyncCallFunctionRaw(context, request, cq));
    }
    virtual ::grpc::Status AllocateMemory(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest& request, ::mombasa::MemoryAllocateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryAllocateResponse>> AsyncAllocateMemory(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryAllocateResponse>>(AsyncAllocateMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryAllocateResponse>> PrepareAsyncAllocateMemory(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryAllocateResponse>>(PrepareAsyncAllocateMemoryRaw(context, request, cq));
    }
    virtual ::grpc::Status FreeMemory(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest& request, ::mombasa::MemoryFreeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryFreeResponse>> AsyncFreeMemory(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryFreeResponse>>(AsyncFreeMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryFreeResponse>> PrepareAsyncFreeMemory(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryFreeResponse>>(PrepareAsyncFreeMemoryRaw(context, request, cq));
    }
    virtual ::grpc::Status ProtectMemory(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest& request, ::mombasa::MemoryProtectResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryProtectResponse>> AsyncProtectMemory(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryProtectResponse>>(AsyncProtectMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryProtectResponse>> PrepareAsyncProtectMemory(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryProtectResponse>>(PrepareAsyncProtectMemoryRaw(context, request, cq));
    }
    virtual ::grpc::Status WriteMemory(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest& request, ::mombasa::MemoryWriteResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryWriteResponse>> AsyncWriteMemory(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryWriteResponse>>(AsyncWriteMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryWriteResponse>> PrepareAsyncWriteMemory(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryWriteResponse>>(PrepareAsyncWriteMemoryRaw(context, request, cq));
    }
    virtual ::grpc::Status ReadMemory(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest& request, ::mombasa::MemoryReadResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryReadResponse>> AsyncReadMemory(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryReadResponse>>(AsyncReadMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryReadResponse>> PrepareAsyncReadMemory(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryReadResponse>>(PrepareAsyncReadMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::mombasa::MemoryReadResponse>> PollMemory(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::mombasa::MemoryReadResponse>>(PollMemoryRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mombasa::MemoryReadResponse>> AsyncPollMemory(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mombasa::MemoryReadResponse>>(AsyncPollMemoryRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mombasa::MemoryReadResponse>> PrepareAsyncPollMemory(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mombasa::MemoryReadResponse>>(PrepareAsyncPollMemoryRaw(context, request, cq));
    }
    virtual ::grpc::Status SetTlsValue(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest& request, ::mombasa::SetTlsValueResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::SetTlsValueResponse>> AsyncSetTlsValue(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::SetTlsValueResponse>>(AsyncSetTlsValueRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::SetTlsValueResponse>> PrepareAsyncSetTlsValue(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::SetTlsValueResponse>>(PrepareAsyncSetTlsValueRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CallFunction(::grpc::ClientContext* context, const ::mombasa::CallRequest* request, ::mombasa::CallResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CallFunction(::grpc::ClientContext* context, const ::mombasa::CallRequest* request, ::mombasa::CallResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void AllocateMemory(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest* request, ::mombasa::MemoryAllocateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AllocateMemory(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest* request, ::mombasa::MemoryAllocateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void FreeMemory(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest* request, ::mombasa::MemoryFreeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FreeMemory(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest* request, ::mombasa::MemoryFreeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ProtectMemory(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest* request, ::mombasa::MemoryProtectResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ProtectMemory(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest* request, ::mombasa::MemoryProtectResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void WriteMemory(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest* request, ::mombasa::MemoryWriteResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void WriteMemory(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest* request, ::mombasa::MemoryWriteResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ReadMemory(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest* request, ::mombasa::MemoryReadResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReadMemory(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest* request, ::mombasa::MemoryReadResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void PollMemory(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest* request, ::grpc::ClientReadReactor< ::mombasa::MemoryReadResponse>* reactor) = 0;
      virtual void SetTlsValue(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest* request, ::mombasa::SetTlsValueResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetTlsValue(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest* request, ::mombasa::SetTlsValueResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::CallResponse>* AsyncCallFunctionRaw(::grpc::ClientContext* context, const ::mombasa::CallRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::CallResponse>* PrepareAsyncCallFunctionRaw(::grpc::ClientContext* context, const ::mombasa::CallRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryAllocateResponse>* AsyncAllocateMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryAllocateResponse>* PrepareAsyncAllocateMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryFreeResponse>* AsyncFreeMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryFreeResponse>* PrepareAsyncFreeMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryProtectResponse>* AsyncProtectMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryProtectResponse>* PrepareAsyncProtectMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryWriteResponse>* AsyncWriteMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryWriteResponse>* PrepareAsyncWriteMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryReadResponse>* AsyncReadMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::MemoryReadResponse>* PrepareAsyncReadMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::mombasa::MemoryReadResponse>* PollMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mombasa::MemoryReadResponse>* AsyncPollMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mombasa::MemoryReadResponse>* PrepareAsyncPollMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::SetTlsValueResponse>* AsyncSetTlsValueRaw(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mombasa::SetTlsValueResponse>* PrepareAsyncSetTlsValueRaw(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CallFunction(::grpc::ClientContext* context, const ::mombasa::CallRequest& request, ::mombasa::CallResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::CallResponse>> AsyncCallFunction(::grpc::ClientContext* context, const ::mombasa::CallRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::CallResponse>>(AsyncCallFunctionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::CallResponse>> PrepareAsyncCallFunction(::grpc::ClientContext* context, const ::mombasa::CallRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::CallResponse>>(PrepareAsyncCallFunctionRaw(context, request, cq));
    }
    ::grpc::Status AllocateMemory(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest& request, ::mombasa::MemoryAllocateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryAllocateResponse>> AsyncAllocateMemory(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryAllocateResponse>>(AsyncAllocateMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryAllocateResponse>> PrepareAsyncAllocateMemory(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryAllocateResponse>>(PrepareAsyncAllocateMemoryRaw(context, request, cq));
    }
    ::grpc::Status FreeMemory(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest& request, ::mombasa::MemoryFreeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryFreeResponse>> AsyncFreeMemory(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryFreeResponse>>(AsyncFreeMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryFreeResponse>> PrepareAsyncFreeMemory(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryFreeResponse>>(PrepareAsyncFreeMemoryRaw(context, request, cq));
    }
    ::grpc::Status ProtectMemory(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest& request, ::mombasa::MemoryProtectResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryProtectResponse>> AsyncProtectMemory(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryProtectResponse>>(AsyncProtectMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryProtectResponse>> PrepareAsyncProtectMemory(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryProtectResponse>>(PrepareAsyncProtectMemoryRaw(context, request, cq));
    }
    ::grpc::Status WriteMemory(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest& request, ::mombasa::MemoryWriteResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryWriteResponse>> AsyncWriteMemory(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryWriteResponse>>(AsyncWriteMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryWriteResponse>> PrepareAsyncWriteMemory(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryWriteResponse>>(PrepareAsyncWriteMemoryRaw(context, request, cq));
    }
    ::grpc::Status ReadMemory(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest& request, ::mombasa::MemoryReadResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryReadResponse>> AsyncReadMemory(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryReadResponse>>(AsyncReadMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryReadResponse>> PrepareAsyncReadMemory(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryReadResponse>>(PrepareAsyncReadMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::mombasa::MemoryReadResponse>> PollMemory(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::mombasa::MemoryReadResponse>>(PollMemoryRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mombasa::MemoryReadResponse>> AsyncPollMemory(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mombasa::MemoryReadResponse>>(AsyncPollMemoryRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mombasa::MemoryReadResponse>> PrepareAsyncPollMemory(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mombasa::MemoryReadResponse>>(PrepareAsyncPollMemoryRaw(context, request, cq));
    }
    ::grpc::Status SetTlsValue(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest& request, ::mombasa::SetTlsValueResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::SetTlsValueResponse>> AsyncSetTlsValue(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::SetTlsValueResponse>>(AsyncSetTlsValueRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::SetTlsValueResponse>> PrepareAsyncSetTlsValue(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mombasa::SetTlsValueResponse>>(PrepareAsyncSetTlsValueRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CallFunction(::grpc::ClientContext* context, const ::mombasa::CallRequest* request, ::mombasa::CallResponse* response, std::function<void(::grpc::Status)>) override;
      void CallFunction(::grpc::ClientContext* context, const ::mombasa::CallRequest* request, ::mombasa::CallResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AllocateMemory(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest* request, ::mombasa::MemoryAllocateResponse* response, std::function<void(::grpc::Status)>) override;
      void AllocateMemory(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest* request, ::mombasa::MemoryAllocateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FreeMemory(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest* request, ::mombasa::MemoryFreeResponse* response, std::function<void(::grpc::Status)>) override;
      void FreeMemory(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest* request, ::mombasa::MemoryFreeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ProtectMemory(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest* request, ::mombasa::MemoryProtectResponse* response, std::function<void(::grpc::Status)>) override;
      void ProtectMemory(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest* request, ::mombasa::MemoryProtectResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void WriteMemory(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest* request, ::mombasa::MemoryWriteResponse* response, std::function<void(::grpc::Status)>) override;
      void WriteMemory(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest* request, ::mombasa::MemoryWriteResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReadMemory(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest* request, ::mombasa::MemoryReadResponse* response, std::function<void(::grpc::Status)>) override;
      void ReadMemory(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest* request, ::mombasa::MemoryReadResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PollMemory(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest* request, ::grpc::ClientReadReactor< ::mombasa::MemoryReadResponse>* reactor) override;
      void SetTlsValue(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest* request, ::mombasa::SetTlsValueResponse* response, std::function<void(::grpc::Status)>) override;
      void SetTlsValue(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest* request, ::mombasa::SetTlsValueResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mombasa::CallResponse>* AsyncCallFunctionRaw(::grpc::ClientContext* context, const ::mombasa::CallRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::CallResponse>* PrepareAsyncCallFunctionRaw(::grpc::ClientContext* context, const ::mombasa::CallRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryAllocateResponse>* AsyncAllocateMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryAllocateResponse>* PrepareAsyncAllocateMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryAllocateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryFreeResponse>* AsyncFreeMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryFreeResponse>* PrepareAsyncFreeMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryFreeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryProtectResponse>* AsyncProtectMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryProtectResponse>* PrepareAsyncProtectMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryProtectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryWriteResponse>* AsyncWriteMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryWriteResponse>* PrepareAsyncWriteMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryWriteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryReadResponse>* AsyncReadMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::MemoryReadResponse>* PrepareAsyncReadMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryReadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::mombasa::MemoryReadResponse>* PollMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest& request) override;
    ::grpc::ClientAsyncReader< ::mombasa::MemoryReadResponse>* AsyncPollMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::mombasa::MemoryReadResponse>* PrepareAsyncPollMemoryRaw(::grpc::ClientContext* context, const ::mombasa::MemoryPollRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::SetTlsValueResponse>* AsyncSetTlsValueRaw(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mombasa::SetTlsValueResponse>* PrepareAsyncSetTlsValueRaw(::grpc::ClientContext* context, const ::mombasa::SetTlsValueRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CallFunction_;
    const ::grpc::internal::RpcMethod rpcmethod_AllocateMemory_;
    const ::grpc::internal::RpcMethod rpcmethod_FreeMemory_;
    const ::grpc::internal::RpcMethod rpcmethod_ProtectMemory_;
    const ::grpc::internal::RpcMethod rpcmethod_WriteMemory_;
    const ::grpc::internal::RpcMethod rpcmethod_ReadMemory_;
    const ::grpc::internal::RpcMethod rpcmethod_PollMemory_;
    const ::grpc::internal::RpcMethod rpcmethod_SetTlsValue_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CallFunction(::grpc::ServerContext* context, const ::mombasa::CallRequest* request, ::mombasa::CallResponse* response);
    virtual ::grpc::Status AllocateMemory(::grpc::ServerContext* context, const ::mombasa::MemoryAllocateRequest* request, ::mombasa::MemoryAllocateResponse* response);
    virtual ::grpc::Status FreeMemory(::grpc::ServerContext* context, const ::mombasa::MemoryFreeRequest* request, ::mombasa::MemoryFreeResponse* response);
    virtual ::grpc::Status ProtectMemory(::grpc::ServerContext* context, const ::mombasa::MemoryProtectRequest* request, ::mombasa::MemoryProtectResponse* response);
    virtual ::grpc::Status WriteMemory(::grpc::ServerContext* context, const ::mombasa::MemoryWriteRequest* request, ::mombasa::MemoryWriteResponse* response);
    virtual ::grpc::Status ReadMemory(::grpc::ServerContext* context, const ::mombasa::MemoryReadRequest* request, ::mombasa::MemoryReadResponse* response);
    virtual ::grpc::Status PollMemory(::grpc::ServerContext* context, const ::mombasa::MemoryPollRequest* request, ::grpc::ServerWriter< ::mombasa::MemoryReadResponse>* writer);
    virtual ::grpc::Status SetTlsValue(::grpc::ServerContext* context, const ::mombasa::SetTlsValueRequest* request, ::mombasa::SetTlsValueResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CallFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CallFunction() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CallFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallFunction(::grpc::ServerContext* /*context*/, const ::mombasa::CallRequest* /*request*/, ::mombasa::CallResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCallFunction(::grpc::ServerContext* context, ::mombasa::CallRequest* request, ::grpc::ServerAsyncResponseWriter< ::mombasa::CallResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AllocateMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AllocateMemory() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AllocateMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryAllocateRequest* /*request*/, ::mombasa::MemoryAllocateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAllocateMemory(::grpc::ServerContext* context, ::mombasa::MemoryAllocateRequest* request, ::grpc::ServerAsyncResponseWriter< ::mombasa::MemoryAllocateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FreeMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FreeMemory() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_FreeMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FreeMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryFreeRequest* /*request*/, ::mombasa::MemoryFreeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFreeMemory(::grpc::ServerContext* context, ::mombasa::MemoryFreeRequest* request, ::grpc::ServerAsyncResponseWriter< ::mombasa::MemoryFreeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ProtectMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProtectMemory() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ProtectMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProtectMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryProtectRequest* /*request*/, ::mombasa::MemoryProtectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProtectMemory(::grpc::ServerContext* context, ::mombasa::MemoryProtectRequest* request, ::grpc::ServerAsyncResponseWriter< ::mombasa::MemoryProtectResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_WriteMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_WriteMemory() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_WriteMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryWriteRequest* /*request*/, ::mombasa::MemoryWriteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWriteMemory(::grpc::ServerContext* context, ::mombasa::MemoryWriteRequest* request, ::grpc::ServerAsyncResponseWriter< ::mombasa::MemoryWriteResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReadMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReadMemory() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_ReadMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryReadRequest* /*request*/, ::mombasa::MemoryReadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadMemory(::grpc::ServerContext* context, ::mombasa::MemoryReadRequest* request, ::grpc::ServerAsyncResponseWriter< ::mombasa::MemoryReadResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PollMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PollMemory() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_PollMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PollMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryPollRequest* /*request*/, ::grpc::ServerWriter< ::mombasa::MemoryReadResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPollMemory(::grpc::ServerContext* context, ::mombasa::MemoryPollRequest* request, ::grpc::ServerAsyncWriter< ::mombasa::MemoryReadResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(6, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetTlsValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetTlsValue() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_SetTlsValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetTlsValue(::grpc::ServerContext* /*context*/, const ::mombasa::SetTlsValueRequest* /*request*/, ::mombasa::SetTlsValueResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetTlsValue(::grpc::ServerContext* context, ::mombasa::SetTlsValueRequest* request, ::grpc::ServerAsyncResponseWriter< ::mombasa::SetTlsValueResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CallFunction<WithAsyncMethod_AllocateMemory<WithAsyncMethod_FreeMemory<WithAsyncMethod_ProtectMemory<WithAsyncMethod_WriteMemory<WithAsyncMethod_ReadMemory<WithAsyncMethod_PollMemory<WithAsyncMethod_SetTlsValue<Service > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CallFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CallFunction() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::mombasa::CallRequest, ::mombasa::CallResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mombasa::CallRequest* request, ::mombasa::CallResponse* response) { return this->CallFunction(context, request, response); }));}
    void SetMessageAllocatorFor_CallFunction(
        ::grpc::MessageAllocator< ::mombasa::CallRequest, ::mombasa::CallResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mombasa::CallRequest, ::mombasa::CallResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CallFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallFunction(::grpc::ServerContext* /*context*/, const ::mombasa::CallRequest* /*request*/, ::mombasa::CallResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CallFunction(
      ::grpc::CallbackServerContext* /*context*/, const ::mombasa::CallRequest* /*request*/, ::mombasa::CallResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AllocateMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AllocateMemory() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::mombasa::MemoryAllocateRequest, ::mombasa::MemoryAllocateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mombasa::MemoryAllocateRequest* request, ::mombasa::MemoryAllocateResponse* response) { return this->AllocateMemory(context, request, response); }));}
    void SetMessageAllocatorFor_AllocateMemory(
        ::grpc::MessageAllocator< ::mombasa::MemoryAllocateRequest, ::mombasa::MemoryAllocateResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mombasa::MemoryAllocateRequest, ::mombasa::MemoryAllocateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AllocateMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryAllocateRequest* /*request*/, ::mombasa::MemoryAllocateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AllocateMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::mombasa::MemoryAllocateRequest* /*request*/, ::mombasa::MemoryAllocateResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FreeMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FreeMemory() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::mombasa::MemoryFreeRequest, ::mombasa::MemoryFreeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mombasa::MemoryFreeRequest* request, ::mombasa::MemoryFreeResponse* response) { return this->FreeMemory(context, request, response); }));}
    void SetMessageAllocatorFor_FreeMemory(
        ::grpc::MessageAllocator< ::mombasa::MemoryFreeRequest, ::mombasa::MemoryFreeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mombasa::MemoryFreeRequest, ::mombasa::MemoryFreeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FreeMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FreeMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryFreeRequest* /*request*/, ::mombasa::MemoryFreeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FreeMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::mombasa::MemoryFreeRequest* /*request*/, ::mombasa::MemoryFreeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ProtectMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ProtectMemory() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::mombasa::MemoryProtectRequest, ::mombasa::MemoryProtectResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mombasa::MemoryProtectRequest* request, ::mombasa::MemoryProtectResponse* response) { return this->ProtectMemory(context, request, response); }));}
    void SetMessageAllocatorFor_ProtectMemory(
        ::grpc::MessageAllocator< ::mombasa::MemoryProtectRequest, ::mombasa::MemoryProtectResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mombasa::MemoryProtectRequest, ::mombasa::MemoryProtectResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ProtectMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProtectMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryProtectRequest* /*request*/, ::mombasa::MemoryProtectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProtectMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::mombasa::MemoryProtectRequest* /*request*/, ::mombasa::MemoryProtectResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_WriteMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_WriteMemory() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::mombasa::MemoryWriteRequest, ::mombasa::MemoryWriteResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mombasa::MemoryWriteRequest* request, ::mombasa::MemoryWriteResponse* response) { return this->WriteMemory(context, request, response); }));}
    void SetMessageAllocatorFor_WriteMemory(
        ::grpc::MessageAllocator< ::mombasa::MemoryWriteRequest, ::mombasa::MemoryWriteResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mombasa::MemoryWriteRequest, ::mombasa::MemoryWriteResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_WriteMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryWriteRequest* /*request*/, ::mombasa::MemoryWriteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* WriteMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::mombasa::MemoryWriteRequest* /*request*/, ::mombasa::MemoryWriteResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReadMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReadMemory() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::mombasa::MemoryReadRequest, ::mombasa::MemoryReadResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mombasa::MemoryReadRequest* request, ::mombasa::MemoryReadResponse* response) { return this->ReadMemory(context, request, response); }));}
    void SetMessageAllocatorFor_ReadMemory(
        ::grpc::MessageAllocator< ::mombasa::MemoryReadRequest, ::mombasa::MemoryReadResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mombasa::MemoryReadRequest, ::mombasa::MemoryReadResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReadMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryReadRequest* /*request*/, ::mombasa::MemoryReadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::mombasa::MemoryReadRequest* /*request*/, ::mombasa::MemoryReadResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PollMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PollMemory() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackServerStreamingHandler< ::mombasa::MemoryPollRequest, ::mombasa::MemoryReadResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mombasa::MemoryPollRequest* request) { return this->PollMemory(context, request); }));
    }
    ~WithCallbackMethod_PollMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PollMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryPollRequest* /*request*/, ::grpc::ServerWriter< ::mombasa::MemoryReadResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::mombasa::MemoryReadResponse>* PollMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::mombasa::MemoryPollRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetTlsValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetTlsValue() {
      ::grpc::Service::MarkMethodCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::mombasa::SetTlsValueRequest, ::mombasa::SetTlsValueResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mombasa::SetTlsValueRequest* request, ::mombasa::SetTlsValueResponse* response) { return this->SetTlsValue(context, request, response); }));}
    void SetMessageAllocatorFor_SetTlsValue(
        ::grpc::MessageAllocator< ::mombasa::SetTlsValueRequest, ::mombasa::SetTlsValueResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(7);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mombasa::SetTlsValueRequest, ::mombasa::SetTlsValueResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetTlsValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetTlsValue(::grpc::ServerContext* /*context*/, const ::mombasa::SetTlsValueRequest* /*request*/, ::mombasa::SetTlsValueResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetTlsValue(
      ::grpc::CallbackServerContext* /*context*/, const ::mombasa::SetTlsValueRequest* /*request*/, ::mombasa::SetTlsValueResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CallFunction<WithCallbackMethod_AllocateMemory<WithCallbackMethod_FreeMemory<WithCallbackMethod_ProtectMemory<WithCallbackMethod_WriteMemory<WithCallbackMethod_ReadMemory<WithCallbackMethod_PollMemory<WithCallbackMethod_SetTlsValue<Service > > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CallFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CallFunction() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CallFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallFunction(::grpc::ServerContext* /*context*/, const ::mombasa::CallRequest* /*request*/, ::mombasa::CallResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AllocateMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AllocateMemory() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AllocateMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryAllocateRequest* /*request*/, ::mombasa::MemoryAllocateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FreeMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FreeMemory() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_FreeMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FreeMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryFreeRequest* /*request*/, ::mombasa::MemoryFreeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ProtectMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProtectMemory() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ProtectMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProtectMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryProtectRequest* /*request*/, ::mombasa::MemoryProtectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_WriteMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_WriteMemory() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_WriteMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryWriteRequest* /*request*/, ::mombasa::MemoryWriteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReadMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReadMemory() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_ReadMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryReadRequest* /*request*/, ::mombasa::MemoryReadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PollMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PollMemory() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_PollMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PollMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryPollRequest* /*request*/, ::grpc::ServerWriter< ::mombasa::MemoryReadResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetTlsValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetTlsValue() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_SetTlsValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetTlsValue(::grpc::ServerContext* /*context*/, const ::mombasa::SetTlsValueRequest* /*request*/, ::mombasa::SetTlsValueResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CallFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CallFunction() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CallFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallFunction(::grpc::ServerContext* /*context*/, const ::mombasa::CallRequest* /*request*/, ::mombasa::CallResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCallFunction(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AllocateMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AllocateMemory() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AllocateMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryAllocateRequest* /*request*/, ::mombasa::MemoryAllocateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAllocateMemory(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FreeMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FreeMemory() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_FreeMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FreeMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryFreeRequest* /*request*/, ::mombasa::MemoryFreeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFreeMemory(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProtectMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProtectMemory() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ProtectMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProtectMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryProtectRequest* /*request*/, ::mombasa::MemoryProtectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProtectMemory(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_WriteMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_WriteMemory() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_WriteMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryWriteRequest* /*request*/, ::mombasa::MemoryWriteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWriteMemory(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReadMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReadMemory() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_ReadMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryReadRequest* /*request*/, ::mombasa::MemoryReadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadMemory(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PollMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PollMemory() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_PollMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PollMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryPollRequest* /*request*/, ::grpc::ServerWriter< ::mombasa::MemoryReadResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPollMemory(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(6, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetTlsValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetTlsValue() {
      ::grpc::Service::MarkMethodRaw(7);
    }
    ~WithRawMethod_SetTlsValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetTlsValue(::grpc::ServerContext* /*context*/, const ::mombasa::SetTlsValueRequest* /*request*/, ::mombasa::SetTlsValueResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetTlsValue(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CallFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CallFunction() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CallFunction(context, request, response); }));
    }
    ~WithRawCallbackMethod_CallFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallFunction(::grpc::ServerContext* /*context*/, const ::mombasa::CallRequest* /*request*/, ::mombasa::CallResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CallFunction(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AllocateMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AllocateMemory() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AllocateMemory(context, request, response); }));
    }
    ~WithRawCallbackMethod_AllocateMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryAllocateRequest* /*request*/, ::mombasa::MemoryAllocateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AllocateMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FreeMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FreeMemory() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FreeMemory(context, request, response); }));
    }
    ~WithRawCallbackMethod_FreeMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FreeMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryFreeRequest* /*request*/, ::mombasa::MemoryFreeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FreeMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ProtectMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ProtectMemory() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ProtectMemory(context, request, response); }));
    }
    ~WithRawCallbackMethod_ProtectMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProtectMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryProtectRequest* /*request*/, ::mombasa::MemoryProtectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProtectMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_WriteMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_WriteMemory() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->WriteMemory(context, request, response); }));
    }
    ~WithRawCallbackMethod_WriteMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryWriteRequest* /*request*/, ::mombasa::MemoryWriteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* WriteMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReadMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReadMemory() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReadMemory(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReadMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryReadRequest* /*request*/, ::mombasa::MemoryReadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PollMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PollMemory() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->PollMemory(context, request); }));
    }
    ~WithRawCallbackMethod_PollMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PollMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryPollRequest* /*request*/, ::grpc::ServerWriter< ::mombasa::MemoryReadResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* PollMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetTlsValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetTlsValue() {
      ::grpc::Service::MarkMethodRawCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetTlsValue(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetTlsValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetTlsValue(::grpc::ServerContext* /*context*/, const ::mombasa::SetTlsValueRequest* /*request*/, ::mombasa::SetTlsValueResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetTlsValue(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CallFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CallFunction() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mombasa::CallRequest, ::mombasa::CallResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mombasa::CallRequest, ::mombasa::CallResponse>* streamer) {
                       return this->StreamedCallFunction(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CallFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CallFunction(::grpc::ServerContext* /*context*/, const ::mombasa::CallRequest* /*request*/, ::mombasa::CallResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCallFunction(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mombasa::CallRequest,::mombasa::CallResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AllocateMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AllocateMemory() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mombasa::MemoryAllocateRequest, ::mombasa::MemoryAllocateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mombasa::MemoryAllocateRequest, ::mombasa::MemoryAllocateResponse>* streamer) {
                       return this->StreamedAllocateMemory(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AllocateMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AllocateMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryAllocateRequest* /*request*/, ::mombasa::MemoryAllocateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAllocateMemory(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mombasa::MemoryAllocateRequest,::mombasa::MemoryAllocateResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FreeMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FreeMemory() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mombasa::MemoryFreeRequest, ::mombasa::MemoryFreeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mombasa::MemoryFreeRequest, ::mombasa::MemoryFreeResponse>* streamer) {
                       return this->StreamedFreeMemory(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FreeMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FreeMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryFreeRequest* /*request*/, ::mombasa::MemoryFreeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFreeMemory(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mombasa::MemoryFreeRequest,::mombasa::MemoryFreeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ProtectMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ProtectMemory() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mombasa::MemoryProtectRequest, ::mombasa::MemoryProtectResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mombasa::MemoryProtectRequest, ::mombasa::MemoryProtectResponse>* streamer) {
                       return this->StreamedProtectMemory(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ProtectMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ProtectMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryProtectRequest* /*request*/, ::mombasa::MemoryProtectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProtectMemory(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mombasa::MemoryProtectRequest,::mombasa::MemoryProtectResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_WriteMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_WriteMemory() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mombasa::MemoryWriteRequest, ::mombasa::MemoryWriteResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mombasa::MemoryWriteRequest, ::mombasa::MemoryWriteResponse>* streamer) {
                       return this->StreamedWriteMemory(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_WriteMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status WriteMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryWriteRequest* /*request*/, ::mombasa::MemoryWriteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedWriteMemory(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mombasa::MemoryWriteRequest,::mombasa::MemoryWriteResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReadMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReadMemory() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mombasa::MemoryReadRequest, ::mombasa::MemoryReadResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mombasa::MemoryReadRequest, ::mombasa::MemoryReadResponse>* streamer) {
                       return this->StreamedReadMemory(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReadMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReadMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryReadRequest* /*request*/, ::mombasa::MemoryReadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReadMemory(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mombasa::MemoryReadRequest,::mombasa::MemoryReadResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetTlsValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetTlsValue() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mombasa::SetTlsValueRequest, ::mombasa::SetTlsValueResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mombasa::SetTlsValueRequest, ::mombasa::SetTlsValueResponse>* streamer) {
                       return this->StreamedSetTlsValue(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetTlsValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetTlsValue(::grpc::ServerContext* /*context*/, const ::mombasa::SetTlsValueRequest* /*request*/, ::mombasa::SetTlsValueResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetTlsValue(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mombasa::SetTlsValueRequest,::mombasa::SetTlsValueResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CallFunction<WithStreamedUnaryMethod_AllocateMemory<WithStreamedUnaryMethod_FreeMemory<WithStreamedUnaryMethod_ProtectMemory<WithStreamedUnaryMethod_WriteMemory<WithStreamedUnaryMethod_ReadMemory<WithStreamedUnaryMethod_SetTlsValue<Service > > > > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_PollMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_PollMemory() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::mombasa::MemoryPollRequest, ::mombasa::MemoryReadResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::mombasa::MemoryPollRequest, ::mombasa::MemoryReadResponse>* streamer) {
                       return this->StreamedPollMemory(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_PollMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PollMemory(::grpc::ServerContext* /*context*/, const ::mombasa::MemoryPollRequest* /*request*/, ::grpc::ServerWriter< ::mombasa::MemoryReadResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedPollMemory(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::mombasa::MemoryPollRequest,::mombasa::MemoryReadResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_PollMemory<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_CallFunction<WithStreamedUnaryMethod_AllocateMemory<WithStreamedUnaryMethod_FreeMemory<WithStreamedUnaryMethod_ProtectMemory<WithStreamedUnaryMethod_WriteMemory<WithStreamedUnaryMethod_ReadMemory<WithSplitStreamingMethod_PollMemory<WithStreamedUnaryMethod_SetTlsValue<Service > > > > > > > > StreamedService;
};

}  // namespace mombasa


#endif  // GRPC_mombasa_2eproto__INCLUDED
