trigger:
- main

variables:
  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/src'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'windows-2022'

    steps:
    - template: install-rust.yml
      parameters:
        rust: nightly
         
    - script: cargo build --release --lib
      workingDirectory: $(workingDirectory)/Superintendent.Native/mombasa
      displayName: cargo build
         
    - task: UseDotNet@2
      displayName: 'Use .NET 6 sdk'
      inputs:
        packageType: sdk
        version: 6.0.x

    - task: DotNetCoreCLI@2
      displayName: Pack Superintendent.Core NuGet
      inputs:
        command: 'pack'
        projects: '$(workingDirectory)/Superintendent.Core/Superintendent.Core.csproj'
        arguments: --configuration Release --output $(Build.ArtifactStagingDirectory)

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop