trigger:
- main

variables:
  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/src'
  vcpkgExportVersion: 'vcpkg-export-20220212-202727'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool: 'Homelab'

    steps:
    - checkout: self
      submodules: true
        
    - task: PowerShell@2
      displayName: 'Setup VCPKG'
      inputs:
        targetType: 'inline'
        script: |
          vcpkg integrate install

    - task: VSBuild@1
      inputs:
        solution: '$(workingDirectory)\Superintendent.Mombasa\Superintendent.Mombasa.vcxproj'
        vsVersion: 'latest'
        platform: 'x64'
        configuration: 'Release'
        msbuildArchitecture: 'x64'
        createLogFile: true
         
    - task: UseDotNet@2
      displayName: 'Use .NET 8 sdk'
      inputs:
        packageType: sdk
        version: 8.0.x
        
    - task: UseDotNet@2
      displayName: 'Use .NET 6 sdk for signtool'
      inputs:
        packageType: sdk
        version: 6.0.x
        
    - task: DotNetCoreCLI@2
      displayName: 'Install Azure SignTool'
      inputs:
        command: custom
        custom: tool
        arguments: 'install --global AzureSignTool'
        
    - task: PowerShell@2
      displayName: 'Sign mombasa'
      condition: ne(variables.AzureKeyVaultClientSecret, '')
      inputs:
        targetType: 'inline'
        script: |
          & AzureSignTool sign -kvu $(AzureKeyVaultUrl) -kvt $(AzureKeyVaultTenantId) -kvi $(AzureKeyVaultClientId) -kvs $(AzureKeyVaultClientSecret) -kvc $(AzureKeyVaultCert) -tr http://timestamp.digicert.com -v "$(workingDirectory)\Superintendent.Mombasa\x64\bin\Release\mombasa.dll"

    - task: DotNetCoreCLI@2
      displayName: Build Superintendent.Core
      inputs:
        command: 'build'
        projects: '$(workingDirectory)/Superintendent.Core/Superintendent.Core.csproj'
        arguments: --configuration Release
        
    - task: PowerShell@2
      displayName: 'Sign Superintendent.Core'
      condition: ne(variables.AzureKeyVaultClientSecret, '')
      inputs:
        targetType: 'inline'
        script: |
          & AzureSignTool sign -kvu $(AzureKeyVaultUrl) -kvt $(AzureKeyVaultTenantId) -kvi $(AzureKeyVaultClientId) -kvs $(AzureKeyVaultClientSecret) -kvc $(AzureKeyVaultCert) -tr http://timestamp.digicert.com --continue-on-error -v "$(workingDirectory)\Superintendent.Core\bin\Release\net6.0\Superintendent.Core.dll"
        
    - task: DotNetCoreCLI@2
      displayName: Pack Superintendent.Core NuGet
      inputs:
        command: 'pack'
        packagesToPack: '$(workingDirectory)/Superintendent.Core/Superintendent.Core.csproj'
        configuration: 'Release'
        nobuild: true
        versioningScheme: 'off'

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop