trigger:
- main

variables:
  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/src'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: BuildND1
    displayName: Build Native Deps1
    pool:
      vmImage: 'windows-2022'

    steps:
    - task: Cache@2
      inputs:
        key: '$(Build.BuildId)-1'
        path: '$(Build.BinariesDirectory)/vcpkg'

    - task: run-vcpkg@0
      inputs:
        vcpkgSetupOnly: true
        vcpkgGitCommitId: '2022.02.02'
        vcpkgTriplet: 'x64-windows-static'
        vcpkgArguments: 'spdlog protobuf openssl'
    
  - job: BuildND2
    dependsOn: BuildND1
    displayName: Build Native Deps2
    pool:
      vmImage: 'windows-2022'

    steps:
    - task: Cache@2
      inputs:
        key: '$(Build.BuildId)-1'
        path: '$(Build.BinariesDirectory)/vcpkg'

    - task: Cache@2
      inputs:
        key: '$(Build.BuildId)-2'
        path: '$(Build.BinariesDirectory)/vcpkg'

    - task: run-vcpkg@0
      inputs:
        vcpkgSetupOnly: true
        vcpkgGitCommitId: '2022.02.02'
        vcpkgTriplet: 'x64-windows'
        vcpkgArguments: 'spdlog protobuf openssl'

  - job: BuildND3
    dependsOn: BuildND2
    displayName: Build Native Deps3
    pool:
      vmImage: 'windows-2022'

    steps:
    - task: Cache@2
      inputs:
        key: '$(Build.BuildId)-1'
        path: '$(Build.BinariesDirectory)/vcpkg'
    - task: Cache@2
      inputs:
        key: '$(Build.BuildId)-2'
        path: '$(Build.BinariesDirectory)/vcpkg'
    - task: Cache@2
      inputs:
        key: '$(Build.BuildId)-3'
        path: '$(Build.BinariesDirectory)/vcpkg'

    - task: run-vcpkg@0
      inputs:
        vcpkgSetupOnly: true
        vcpkgGitCommitId: '2022.02.02'
        vcpkgTriplet: 'x64-windows-static'
        vcpkgArguments: 'grpc'


  - job: Build
    dependsOn: BuildND3
    displayName: Build
    pool:
      vmImage: 'windows-2022'

    steps:
    - task: Cache@2
      inputs:
        key: '$(Build.BuildId)-1'
        path: '$(Build.BinariesDirectory)/vcpkg'
    - task: Cache@2
      inputs:
        key: '$(Build.BuildId)-2'
        path: '$(Build.BinariesDirectory)/vcpkg'
    - task: Cache@2
      inputs:
        key: '$(Build.BuildId)-3'
        path: '$(Build.BinariesDirectory)/vcpkg'

    - task: run-vcpkg@0
      inputs:
        vcpkgSetupOnly: true
        vcpkgGitCommitId: '2022.02.02'
        vcpkgTriplet: 'x64-windows-static'
        vcpkgArguments: 'spdlog'
    
    - task: CmdLine@2
      inputs:
        script: '$(Build.BinariesDirectory)\vcpkg\vcpkg.exe install --triplet x64-windows-static'
        workingDirectory: '$(workingDirectory)\Superintendent.Mombasa'

    - task: VSBuild@1
      inputs:
        solution: '$(workingDirectory)\Superintendent.Mombasa\Superintendent.Mombasa.vcxproj'
        vsVersion: '17.0'
        platform: 'x64'
        configuration: 'Release'
        msbuildArchitecture: 'x64'
        createLogFile: true

    # latest nightly may not have rustfmt/clippy
    # we can't check for both:
    # https://github.com/rust-lang/rustup-components-history/issues/9
    # but we at least check for one.
    # rustfmt _seems_ to break most often:
    - bash: |
        echo '##vso[task.setvariable variable=nightly]nightly-'$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/rustfmt)
      displayName: "Determine latest style nightly"
    - template: install-rust.yml
      parameters:
        rust: $(nightly)
        components:
          - rustfmt
          - clippy
         
    - script: cargo build --release --lib
      workingDirectory: $(workingDirectory)/Superintendent.Native/mombasa
      displayName: cargo build
         
    - task: UseDotNet@2
      displayName: 'Use .NET 6 sdk'
      inputs:
        packageType: sdk
        version: 6.0.x

    - task: DotNetCoreCLI@2
      displayName: Pack Superintendent.Core NuGet
      inputs:
        command: 'pack'
        projects: '$(workingDirectory)/Superintendent.Core/Superintendent.Core.csproj'
        arguments: --configuration Release --output $(Build.ArtifactStagingDirectory)

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop